### ISSUE TITLE
Error in UseMethod("mutate_")

### ISSUE THREAD

**Issue by jrk1** [methodds/facerec#4]
Hi,

I just tried running your tutorial example as well as running the code on an own image. Both times, I get the following error:

Error in UseMethod("mutate_") : 
  no applicable method for 'mutate_' applied to an object of class "NULL"
In addition: Warning message:
`mutate_()` is deprecated as of dplyr 0.7.0.
Please use `mutate()` instead.

**Comment by cschwem2er** [comment]
Hi,

as stated in the readme, the package is not maintained anymore because Kairos API stopped to provide free access for its API and the corresponding features for which facerec was once a wrapper.
